### ISSUE TITLE
Repository Structure

### ISSUE THREAD

**Issue by ElectronicsArchiver** [breakinblocks/BBChat#2]
<br>

I would recommend using a `/Source/` folder
to reduce cluttering the root folder of the repo.

<br>

**Comment by BlueAgent** [comment]
Was thinking of moving the Forge code into a folder so it'd look something like:

```
/bbchat-common
/bbchat-forge
/bbchat-forge/latest
/bbchat-forge/[v|mc]1.18.2
...
```

But not sure yet. It's probably a bit questionable not using branches for each Minecraft version but I kinda wanted to just have one mega project. Maybe it could be done with git sub-modules...?

I'm a bit hesitant to call it a source folder though because it also contains resources as well. Would probably describe them as Gradle sub-projects perhaps. A sub-projects or projects folder could be an option, not sure I like that though.

Removing the `bbchat-` prefix on the folders might also be an idea?

Or maybe the "source" / "project" folder could be called "bbchat".

**Comment by ElectronicsArchiver** [comment]
Well /Source/ usually refers to everything that makes up the program / mod / plugin / ..

A /Resources/ folder on root level can be understood as ffor things used outside program / .. but in the project, like documentation images, logos, ..

You can simply create a /Resources/ or /Assets/ folder in the /Source/ folder for those things.

Btw, are those forge specific version folders any different in code than the generic one?
If not, if they are just meant for publishing, you might as well not include them in the repository at all and just provide them as zip / tar in the releases only.

If you do need them, non-locally, I would advice using a /Forge/X.X.X/ structure or branches.

**Comment by BlueAgent** [comment]
I don't think we're going to be adding any kind of extensive documentation or art resources to the repo. At most the README might get updated for how to get things set up.

As for the sub-projects, it's already like that to some extent I think:

```
/bbchat-forge/src/main/java
/bbchat-forge/src/main/resources
```

The forge specific version folders do have different code (although the more recent ones are similar) we need to make sure they compile on each of the supported platforms and minecraft versions. The code they share in common is in the `bbchat-common` sub-project.

It's kinda like what [Spark](https://github.com/lucko/spark), [Fabric](https://github.com/FabricMC/fabric) and [Tokio](https://github.com/tokio-rs/tokio) do.

Eventually the plan is to add support for mod loaders other than Forge. Like Fabric and Quilt.

I think the one I like the most so far is a structure like mentioned in my previous comment, which is similar to Spark's repository layout for each of the projects. But with sub-folders for the supported minecraft versions.

```
/bbchat-common/
/bbchat-fabric/latest
/bbchat-fabric/v1.18.2
/bbchat-fabric/v1.16.5
/bbchat-forge/latest
/bbchat-forge/v1.18.2
/bbchat-forge/v1.16.5
/bbchat-quilt/latest
/bbchat-quilt/1.18.2
```

Although, not totally sure, because should we want to use sub-modules for each minecraft version, it would be something like:

```
/bbchat-common/
/bbchat-mc/fabric
/bbchat-mc/forge
/bbchat-mc/quilt
/bbchat-mc-1.18.2/fabric
/bbchat-mc-1.18.2/forge
/bbchat-mc-1.18.2/quilt
/bbchat-mc-1.16.5/fabric
/bbchat-mc-1.16.5/forge
/bbchat-mc-1.12.2/forge
/bbchat-mc-1.7.10/forge
```

We could have a submodule for each platform-minecraft_version pair instead and keep the former layout.

If we wanted the sub-projects themselves to be compilable, they'd need to have the common code as a submodule I think...

But, dealing with sub-modules just takes me back to having many copies of different branches of the repo and that wasn't fun. Although it would make any changes less repetitive in the history diff, it would still need to mirror the changes to the other sub-modules anyway.

The project is done in this way because it was supporting so many Minecraft versions.
Initially it was for 1.15.x because there weren't any Discord relays for that version of the game yet, but then got back-ported to older versions of the game since Discord's API updated and the Discord relay mods we were using stopped working.

**Comment by ElectronicsArchiver** [comment]
Well sub-modules are a pain anyways, so I wouldn't want to touch them in the first place..

And how about a simpler structure like:

```
/Source/
    /Common/
    /Fabric/
        /Latest/
        /1.18.2/
    /Forge/
        /Latest/
        /1.18.2/
    /Quilt/
        /Latest/
        /1.18.2/
```

**Comment by BlueAgent** [comment]
If it happens it'll probably be called `src` to match with the project structure the Java plugin for gradle uses by default.

Will give this some time and decide on something closer to porting the mod to Fabric and Quilt.

**Comment by BlueAgent** [comment]
Reorganized to use the following layout:
```
projects/
    core/
    minecraft/
        latest/
            common/
            fabric/
            forge/
            quilt/
        v1.18.2/
            common/
            fabric/
            forge/
            quilt/
        v1.17.1/
            ...
        v1.16.5/
            ...
        v1.15.2/
            ...
        v1.14.4/
            ...
        v1.12.2/
            ...
        v1.7.10/
            ...
gradle/
    wrapper/
        ...
.gitattributes
.gitignore
LICENSE
...
```
